/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as BackofficeRouteImport } from './routes/backoffice'
import { Route as CommentCaMarcheRouteImport } from './routes/comment-ca-marche'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DemandeRouteImport } from './routes/demande'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as BackofficeIndexRouteImport } from './routes/backoffice.index'
import { Route as BackofficeClientsRouteImport } from './routes/backoffice.clients'
import { Route as BackofficeCoursesRouteImport } from './routes/backoffice.courses'
import { Route as BackofficeCoursiersRouteImport } from './routes/backoffice.coursiers'
import { Route as BackofficeDashboardRouteImport } from './routes/backoffice.dashboard'
import { Route as BackofficeDemandesRouteImport } from './routes/backoffice.demandes'
import { Route as BackofficeDocumentsRouteImport } from './routes/backoffice.documents'
import { Route as BackofficeDossiersRouteImport } from './routes/backoffice.dossiers'
import { Route as BackofficeFacturationRouteImport } from './routes/backoffice.facturation'
import { Route as BackofficeFournisseursRouteImport } from './routes/backoffice.fournisseurs'
import { Route as BackofficePaiementsRouteImport } from './routes/backoffice.paiements'
import { Route as BackofficeProceduresRouteImport } from './routes/backoffice.procedures'
import { Route as BackofficeRapportsRouteImport } from './routes/backoffice.rapports'
import { Route as BackofficeWhatsappRouteImport } from './routes/backoffice.whatsapp'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const BackofficeRoute = BackofficeRouteImport.update({
  id: '/backoffice',
  path: '/backoffice',
  getParentRoute: () => rootRouteImport,
} as any)
const CommentCaMarcheRoute = CommentCaMarcheRouteImport.update({
  id: '/comment-ca-marche',
  path: '/comment-ca-marche',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DemandeRoute = DemandeRouteImport.update({
  id: '/demande',
  path: '/demande',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const BackofficeIndexRoute = BackofficeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeClientsRoute = BackofficeClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeCoursesRoute = BackofficeCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeCoursiersRoute = BackofficeCoursiersRouteImport.update({
  id: '/coursiers',
  path: '/coursiers',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeDashboardRoute = BackofficeDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeDemandesRoute = BackofficeDemandesRouteImport.update({
  id: '/demandes',
  path: '/demandes',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeDocumentsRoute = BackofficeDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeDossiersRoute = BackofficeDossiersRouteImport.update({
  id: '/dossiers',
  path: '/dossiers',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeFacturationRoute = BackofficeFacturationRouteImport.update({
  id: '/facturation',
  path: '/facturation',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeFournisseursRoute = BackofficeFournisseursRouteImport.update({
  id: '/fournisseurs',
  path: '/fournisseurs',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficePaiementsRoute = BackofficePaiementsRouteImport.update({
  id: '/paiements',
  path: '/paiements',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeProceduresRoute = BackofficeProceduresRouteImport.update({
  id: '/procedures',
  path: '/procedures',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeRapportsRoute = BackofficeRapportsRouteImport.update({
  id: '/rapports',
  path: '/rapports',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeWhatsappRoute = BackofficeWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => BackofficeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/backoffice': typeof BackofficeRouteWithChildren
  '/comment-ca-marche': typeof CommentCaMarcheRoute
  '/connexion': typeof ConnexionRoute
  '/contact': typeof ContactRoute
  '/demande': typeof DemandeRoute
  '/services': typeof ServicesRoute
  '/backoffice/clients': typeof BackofficeClientsRoute
  '/backoffice/courses': typeof BackofficeCoursesRoute
  '/backoffice/coursiers': typeof BackofficeCoursiersRoute
  '/backoffice/dashboard': typeof BackofficeDashboardRoute
  '/backoffice/demandes': typeof BackofficeDemandesRoute
  '/backoffice/documents': typeof BackofficeDocumentsRoute
  '/backoffice/dossiers': typeof BackofficeDossiersRoute
  '/backoffice/facturation': typeof BackofficeFacturationRoute
  '/backoffice/fournisseurs': typeof BackofficeFournisseursRoute
  '/backoffice/paiements': typeof BackofficePaiementsRoute
  '/backoffice/procedures': typeof BackofficeProceduresRoute
  '/backoffice/rapports': typeof BackofficeRapportsRoute
  '/backoffice/whatsapp': typeof BackofficeWhatsappRoute
  '/backoffice/': typeof BackofficeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/comment-ca-marche': typeof CommentCaMarcheRoute
  '/connexion': typeof ConnexionRoute
  '/contact': typeof ContactRoute
  '/demande': typeof DemandeRoute
  '/services': typeof ServicesRoute
  '/backoffice/clients': typeof BackofficeClientsRoute
  '/backoffice/courses': typeof BackofficeCoursesRoute
  '/backoffice/coursiers': typeof BackofficeCoursiersRoute
  '/backoffice/dashboard': typeof BackofficeDashboardRoute
  '/backoffice/demandes': typeof BackofficeDemandesRoute
  '/backoffice/documents': typeof BackofficeDocumentsRoute
  '/backoffice/dossiers': typeof BackofficeDossiersRoute
  '/backoffice/facturation': typeof BackofficeFacturationRoute
  '/backoffice/fournisseurs': typeof BackofficeFournisseursRoute
  '/backoffice/paiements': typeof BackofficePaiementsRoute
  '/backoffice/procedures': typeof BackofficeProceduresRoute
  '/backoffice/rapports': typeof BackofficeRapportsRoute
  '/backoffice/whatsapp': typeof BackofficeWhatsappRoute
  '/backoffice': typeof BackofficeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/backoffice': typeof BackofficeRouteWithChildren
  '/comment-ca-marche': typeof CommentCaMarcheRoute
  '/connexion': typeof ConnexionRoute
  '/contact': typeof ContactRoute
  '/demande': typeof DemandeRoute
  '/services': typeof ServicesRoute
  '/backoffice/clients': typeof BackofficeClientsRoute
  '/backoffice/courses': typeof BackofficeCoursesRoute
  '/backoffice/coursiers': typeof BackofficeCoursiersRoute
  '/backoffice/dashboard': typeof BackofficeDashboardRoute
  '/backoffice/demandes': typeof BackofficeDemandesRoute
  '/backoffice/documents': typeof BackofficeDocumentsRoute
  '/backoffice/dossiers': typeof BackofficeDossiersRoute
  '/backoffice/facturation': typeof BackofficeFacturationRoute
  '/backoffice/fournisseurs': typeof BackofficeFournisseursRoute
  '/backoffice/paiements': typeof BackofficePaiementsRoute
  '/backoffice/procedures': typeof BackofficeProceduresRoute
  '/backoffice/rapports': typeof BackofficeRapportsRoute
  '/backoffice/whatsapp': typeof BackofficeWhatsappRoute
  '/backoffice/': typeof BackofficeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/backoffice'
    | '/comment-ca-marche'
    | '/connexion'
    | '/contact'
    | '/demande'
    | '/services'
    | '/backoffice/clients'
    | '/backoffice/courses'
    | '/backoffice/coursiers'
    | '/backoffice/dashboard'
    | '/backoffice/demandes'
    | '/backoffice/documents'
    | '/backoffice/dossiers'
    | '/backoffice/facturation'
    | '/backoffice/fournisseurs'
    | '/backoffice/paiements'
    | '/backoffice/procedures'
    | '/backoffice/rapports'
    | '/backoffice/whatsapp'
    | '/backoffice/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/comment-ca-marche'
    | '/connexion'
    | '/contact'
    | '/demande'
    | '/services'
    | '/backoffice/clients'
    | '/backoffice/courses'
    | '/backoffice/coursiers'
    | '/backoffice/dashboard'
    | '/backoffice/demandes'
    | '/backoffice/documents'
    | '/backoffice/dossiers'
    | '/backoffice/facturation'
    | '/backoffice/fournisseurs'
    | '/backoffice/paiements'
    | '/backoffice/procedures'
    | '/backoffice/rapports'
    | '/backoffice/whatsapp'
    | '/backoffice'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/backoffice'
    | '/comment-ca-marche'
    | '/connexion'
    | '/contact'
    | '/demande'
    | '/services'
    | '/backoffice/clients'
    | '/backoffice/courses'
    | '/backoffice/coursiers'
    | '/backoffice/dashboard'
    | '/backoffice/demandes'
    | '/backoffice/documents'
    | '/backoffice/dossiers'
    | '/backoffice/facturation'
    | '/backoffice/fournisseurs'
    | '/backoffice/paiements'
    | '/backoffice/procedures'
    | '/backoffice/rapports'
    | '/backoffice/whatsapp'
    | '/backoffice/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  BackofficeRoute: typeof BackofficeRouteWithChildren
  CommentCaMarcheRoute: typeof CommentCaMarcheRoute
  ConnexionRoute: typeof ConnexionRoute
  ContactRoute: typeof ContactRoute
  DemandeRoute: typeof DemandeRoute
  ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backoffice': {
      id: '/backoffice'
      path: '/backoffice'
      fullPath: '/backoffice'
      preLoaderRoute: typeof BackofficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comment-ca-marche': {
      id: '/comment-ca-marche'
      path: '/comment-ca-marche'
      fullPath: '/comment-ca-marche'
      preLoaderRoute: typeof CommentCaMarcheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demande': {
      id: '/demande'
      path: '/demande'
      fullPath: '/demande'
      preLoaderRoute: typeof DemandeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backoffice/': {
      id: '/backoffice/'
      path: '/'
      fullPath: '/backoffice/'
      preLoaderRoute: typeof BackofficeIndexRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/backoffice/clients': {
      id: '/backoffice/clients'
      path: '/clients'
      fullPath: '/backoffice/clients'
      preLoaderRoute: typeof BackofficeClientsRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/backoffice/courses': {
      id: '/backoffice/courses'
      path: '/courses'
      fullPath: '/backoffice/courses'
      preLoaderRoute: typeof BackofficeCoursesRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/backoffice/coursiers': {
      id: '/backoffice/coursiers'
      path: '/coursiers'
      fullPath: '/backoffice/coursiers'
      preLoaderRoute: typeof BackofficeCoursiersRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/backoffice/dashboard': {
      id: '/backoffice/dashboard'
      path: '/dashboard'
      fullPath: '/backoffice/dashboard'
      preLoaderRoute: typeof BackofficeDashboardRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/backoffice/demandes': {
      id: '/backoffice/demandes'
      path: '/demandes'
      fullPath: '/backoffice/demandes'
      preLoaderRoute: typeof BackofficeDemandesRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/backoffice/documents': {
      id: '/backoffice/documents'
      path: '/documents'
      fullPath: '/backoffice/documents'
      preLoaderRoute: typeof BackofficeDocumentsRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/backoffice/dossiers': {
      id: '/backoffice/dossiers'
      path: '/dossiers'
      fullPath: '/backoffice/dossiers'
      preLoaderRoute: typeof BackofficeDossiersRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/backoffice/facturation': {
      id: '/backoffice/facturation'
      path: '/facturation'
      fullPath: '/backoffice/facturation'
      preLoaderRoute: typeof BackofficeFacturationRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/backoffice/fournisseurs': {
      id: '/backoffice/fournisseurs'
      path: '/fournisseurs'
      fullPath: '/backoffice/fournisseurs'
      preLoaderRoute: typeof BackofficeFournisseursRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/backoffice/paiements': {
      id: '/backoffice/paiements'
      path: '/paiements'
      fullPath: '/backoffice/paiements'
      preLoaderRoute: typeof BackofficePaiementsRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/backoffice/procedures': {
      id: '/backoffice/procedures'
      path: '/procedures'
      fullPath: '/backoffice/procedures'
      preLoaderRoute: typeof BackofficeProceduresRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/backoffice/rapports': {
      id: '/backoffice/rapports'
      path: '/rapports'
      fullPath: '/backoffice/rapports'
      preLoaderRoute: typeof BackofficeRapportsRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/backoffice/whatsapp': {
      id: '/backoffice/whatsapp'
      path: '/whatsapp'
      fullPath: '/backoffice/whatsapp'
      preLoaderRoute: typeof BackofficeWhatsappRouteImport
      parentRoute: typeof BackofficeRoute
    }
  }
}

interface BackofficeRouteChildren {
  BackofficeClientsRoute: typeof BackofficeClientsRoute
  BackofficeCoursesRoute: typeof BackofficeCoursesRoute
  BackofficeCoursiersRoute: typeof BackofficeCoursiersRoute
  BackofficeDashboardRoute: typeof BackofficeDashboardRoute
  BackofficeDemandesRoute: typeof BackofficeDemandesRoute
  BackofficeDocumentsRoute: typeof BackofficeDocumentsRoute
  BackofficeDossiersRoute: typeof BackofficeDossiersRoute
  BackofficeFacturationRoute: typeof BackofficeFacturationRoute
  BackofficeFournisseursRoute: typeof BackofficeFournisseursRoute
  BackofficePaiementsRoute: typeof BackofficePaiementsRoute
  BackofficeProceduresRoute: typeof BackofficeProceduresRoute
  BackofficeRapportsRoute: typeof BackofficeRapportsRoute
  BackofficeWhatsappRoute: typeof BackofficeWhatsappRoute
  BackofficeIndexRoute: typeof BackofficeIndexRoute
}

const BackofficeRouteChildren: BackofficeRouteChildren = {
  BackofficeClientsRoute: BackofficeClientsRoute,
  BackofficeCoursesRoute: BackofficeCoursesRoute,
  BackofficeCoursiersRoute: BackofficeCoursiersRoute,
  BackofficeDashboardRoute: BackofficeDashboardRoute,
  BackofficeDemandesRoute: BackofficeDemandesRoute,
  BackofficeDocumentsRoute: BackofficeDocumentsRoute,
  BackofficeDossiersRoute: BackofficeDossiersRoute,
  BackofficeFacturationRoute: BackofficeFacturationRoute,
  BackofficeFournisseursRoute: BackofficeFournisseursRoute,
  BackofficePaiementsRoute: BackofficePaiementsRoute,
  BackofficeProceduresRoute: BackofficeProceduresRoute,
  BackofficeRapportsRoute: BackofficeRapportsRoute,
  BackofficeWhatsappRoute: BackofficeWhatsappRoute,
  BackofficeIndexRoute: BackofficeIndexRoute,
}

const BackofficeRouteWithChildren = BackofficeRoute._addFileChildren(
  BackofficeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  BackofficeRoute: BackofficeRouteWithChildren,
  CommentCaMarcheRoute: CommentCaMarcheRoute,
  ConnexionRoute: ConnexionRoute,
  ContactRoute: ContactRoute,
  DemandeRoute: DemandeRoute,
  ServicesRoute: ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
