/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BackofficeRouteImport } from './routes/backoffice'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as BackofficeIndexRouteImport } from './routes/backoffice.index'
import { Route as BackofficeClientsRouteImport } from './routes/backoffice.clients'
import { Route as BackofficeCoursiersRouteImport } from './routes/backoffice.coursiers'
import { Route as BackofficeDashboardRouteImport } from './routes/backoffice.dashboard'
import { Route as BackofficeDemandesRouteImport } from './routes/backoffice.demandes'
import { Route as BackofficeDispatchRouteImport } from './routes/backoffice.dispatch'
import { Route as BackofficeDossiersRouteImport } from './routes/backoffice.dossiers'
import { Route as BackofficeFacturationRouteImport } from './routes/backoffice.facturation'
import { Route as BackofficeFournisseursRouteImport } from './routes/backoffice.fournisseurs'
import { Route as BackofficeParametresRouteImport } from './routes/backoffice.parametres'
import { Route as BackofficeProceduresRouteImport } from './routes/backoffice.procedures'
import { Route as BackofficeRapportsRouteImport } from './routes/backoffice.rapports'
import { Route as BackofficeWhatsappRouteImport } from './routes/backoffice.whatsapp'
import { Route as SiteIndexRouteImport } from './routes/site/index'
import { Route as SiteAProposRouteImport } from './routes/site/a-propos'
import { Route as SiteCommentCaMarcheRouteImport } from './routes/site/comment-ca-marche'
import { Route as SiteContactRouteImport } from './routes/site/contact'
import { Route as SiteDemandeRouteImport } from './routes/site/demande'
import { Route as SiteServicesRouteImport } from './routes/site/services'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BackofficeRoute = BackofficeRouteImport.update({
  id: '/backoffice',
  path: '/backoffice',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const BackofficeIndexRoute = BackofficeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeClientsRoute = BackofficeClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeCoursiersRoute = BackofficeCoursiersRouteImport.update({
  id: '/coursiers',
  path: '/coursiers',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeDashboardRoute = BackofficeDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeDemandesRoute = BackofficeDemandesRouteImport.update({
  id: '/demandes',
  path: '/demandes',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeDispatchRoute = BackofficeDispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeDossiersRoute = BackofficeDossiersRouteImport.update({
  id: '/dossiers',
  path: '/dossiers',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeFacturationRoute = BackofficeFacturationRouteImport.update({
  id: '/facturation',
  path: '/facturation',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeFournisseursRoute = BackofficeFournisseursRouteImport.update({
  id: '/fournisseurs',
  path: '/fournisseurs',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeParametresRoute = BackofficeParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeProceduresRoute = BackofficeProceduresRouteImport.update({
  id: '/procedures',
  path: '/procedures',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeRapportsRoute = BackofficeRapportsRouteImport.update({
  id: '/rapports',
  path: '/rapports',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeWhatsappRoute = BackofficeWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => BackofficeRoute,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/site/',
  path: '/site/',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteAProposRoute = SiteAProposRouteImport.update({
  id: '/site/a-propos',
  path: '/site/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteCommentCaMarcheRoute = SiteCommentCaMarcheRouteImport.update({
  id: '/site/comment-ca-marche',
  path: '/site/comment-ca-marche',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/site/contact',
  path: '/site/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteDemandeRoute = SiteDemandeRouteImport.update({
  id: '/site/demande',
  path: '/site/demande',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteServicesRoute = SiteServicesRouteImport.update({
  id: '/site/services',
  path: '/site/services',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backoffice': typeof BackofficeRouteWithChildren
  '/connexion': typeof ConnexionRoute
  '/backoffice/clients': typeof BackofficeClientsRoute
  '/backoffice/coursiers': typeof BackofficeCoursiersRoute
  '/backoffice/dashboard': typeof BackofficeDashboardRoute
  '/backoffice/demandes': typeof BackofficeDemandesRoute
  '/backoffice/dispatch': typeof BackofficeDispatchRoute
  '/backoffice/dossiers': typeof BackofficeDossiersRoute
  '/backoffice/facturation': typeof BackofficeFacturationRoute
  '/backoffice/fournisseurs': typeof BackofficeFournisseursRoute
  '/backoffice/parametres': typeof BackofficeParametresRoute
  '/backoffice/procedures': typeof BackofficeProceduresRoute
  '/backoffice/rapports': typeof BackofficeRapportsRoute
  '/backoffice/whatsapp': typeof BackofficeWhatsappRoute
  '/site/a-propos': typeof SiteAProposRoute
  '/site/comment-ca-marche': typeof SiteCommentCaMarcheRoute
  '/site/contact': typeof SiteContactRoute
  '/site/demande': typeof SiteDemandeRoute
  '/site/services': typeof SiteServicesRoute
  '/backoffice/': typeof BackofficeIndexRoute
  '/site/': typeof SiteIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connexion': typeof ConnexionRoute
  '/backoffice/clients': typeof BackofficeClientsRoute
  '/backoffice/coursiers': typeof BackofficeCoursiersRoute
  '/backoffice/dashboard': typeof BackofficeDashboardRoute
  '/backoffice/demandes': typeof BackofficeDemandesRoute
  '/backoffice/dispatch': typeof BackofficeDispatchRoute
  '/backoffice/dossiers': typeof BackofficeDossiersRoute
  '/backoffice/facturation': typeof BackofficeFacturationRoute
  '/backoffice/fournisseurs': typeof BackofficeFournisseursRoute
  '/backoffice/parametres': typeof BackofficeParametresRoute
  '/backoffice/procedures': typeof BackofficeProceduresRoute
  '/backoffice/rapports': typeof BackofficeRapportsRoute
  '/backoffice/whatsapp': typeof BackofficeWhatsappRoute
  '/site/a-propos': typeof SiteAProposRoute
  '/site/comment-ca-marche': typeof SiteCommentCaMarcheRoute
  '/site/contact': typeof SiteContactRoute
  '/site/demande': typeof SiteDemandeRoute
  '/site/services': typeof SiteServicesRoute
  '/backoffice': typeof BackofficeIndexRoute
  '/site': typeof SiteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backoffice': typeof BackofficeRouteWithChildren
  '/connexion': typeof ConnexionRoute
  '/backoffice/clients': typeof BackofficeClientsRoute
  '/backoffice/coursiers': typeof BackofficeCoursiersRoute
  '/backoffice/dashboard': typeof BackofficeDashboardRoute
  '/backoffice/demandes': typeof BackofficeDemandesRoute
  '/backoffice/dispatch': typeof BackofficeDispatchRoute
  '/backoffice/dossiers': typeof BackofficeDossiersRoute
  '/backoffice/facturation': typeof BackofficeFacturationRoute
  '/backoffice/fournisseurs': typeof BackofficeFournisseursRoute
  '/backoffice/parametres': typeof BackofficeParametresRoute
  '/backoffice/procedures': typeof BackofficeProceduresRoute
  '/backoffice/rapports': typeof BackofficeRapportsRoute
  '/backoffice/whatsapp': typeof BackofficeWhatsappRoute
  '/site/a-propos': typeof SiteAProposRoute
  '/site/comment-ca-marche': typeof SiteCommentCaMarcheRoute
  '/site/contact': typeof SiteContactRoute
  '/site/demande': typeof SiteDemandeRoute
  '/site/services': typeof SiteServicesRoute
  '/backoffice/': typeof BackofficeIndexRoute
  '/site/': typeof SiteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backoffice'
    | '/connexion'
    | '/backoffice/clients'
    | '/backoffice/coursiers'
    | '/backoffice/dashboard'
    | '/backoffice/demandes'
    | '/backoffice/dispatch'
    | '/backoffice/dossiers'
    | '/backoffice/facturation'
    | '/backoffice/fournisseurs'
    | '/backoffice/parametres'
    | '/backoffice/procedures'
    | '/backoffice/rapports'
    | '/backoffice/whatsapp'
    | '/site/a-propos'
    | '/site/comment-ca-marche'
    | '/site/contact'
    | '/site/demande'
    | '/site/services'
    | '/backoffice/'
    | '/site/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connexion'
    | '/backoffice/clients'
    | '/backoffice/coursiers'
    | '/backoffice/dashboard'
    | '/backoffice/demandes'
    | '/backoffice/dispatch'
    | '/backoffice/dossiers'
    | '/backoffice/facturation'
    | '/backoffice/fournisseurs'
    | '/backoffice/parametres'
    | '/backoffice/procedures'
    | '/backoffice/rapports'
    | '/backoffice/whatsapp'
    | '/site/a-propos'
    | '/site/comment-ca-marche'
    | '/site/contact'
    | '/site/demande'
    | '/site/services'
    | '/backoffice'
    | '/site'
  id:
    | '__root__'
    | '/'
    | '/backoffice'
    | '/connexion'
    | '/backoffice/clients'
    | '/backoffice/coursiers'
    | '/backoffice/dashboard'
    | '/backoffice/demandes'
    | '/backoffice/dispatch'
    | '/backoffice/dossiers'
    | '/backoffice/facturation'
    | '/backoffice/fournisseurs'
    | '/backoffice/parametres'
    | '/backoffice/procedures'
    | '/backoffice/rapports'
    | '/backoffice/whatsapp'
    | '/site/a-propos'
    | '/site/comment-ca-marche'
    | '/site/contact'
    | '/site/demande'
    | '/site/services'
    | '/backoffice/'
    | '/site/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BackofficeRoute: typeof BackofficeRouteWithChildren
  ConnexionRoute: typeof ConnexionRoute
  SiteAProposRoute: typeof SiteAProposRoute
  SiteCommentCaMarcheRoute: typeof SiteCommentCaMarcheRoute
  SiteContactRoute: typeof SiteContactRoute
  SiteDemandeRoute: typeof SiteDemandeRoute
  SiteServicesRoute: typeof SiteServicesRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backoffice': {
      id: '/backoffice'
      path: '/backoffice'
      fullPath: '/backoffice'
      preLoaderRoute: typeof BackofficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backoffice/': {
      id: '/backoffice/'
      path: '/'
      fullPath: '/backoffice/'
      preLoaderRoute: typeof BackofficeIndexRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/backoffice/clients': {
      id: '/backoffice/clients'
      path: '/clients'
      fullPath: '/backoffice/clients'
      preLoaderRoute: typeof BackofficeClientsRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/backoffice/coursiers': {
      id: '/backoffice/coursiers'
      path: '/coursiers'
      fullPath: '/backoffice/coursiers'
      preLoaderRoute: typeof BackofficeCoursiersRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/backoffice/dashboard': {
      id: '/backoffice/dashboard'
      path: '/dashboard'
      fullPath: '/backoffice/dashboard'
      preLoaderRoute: typeof BackofficeDashboardRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/backoffice/demandes': {
      id: '/backoffice/demandes'
      path: '/demandes'
      fullPath: '/backoffice/demandes'
      preLoaderRoute: typeof BackofficeDemandesRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/backoffice/dispatch': {
      id: '/backoffice/dispatch'
      path: '/dispatch'
      fullPath: '/backoffice/dispatch'
      preLoaderRoute: typeof BackofficeDispatchRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/backoffice/dossiers': {
      id: '/backoffice/dossiers'
      path: '/dossiers'
      fullPath: '/backoffice/dossiers'
      preLoaderRoute: typeof BackofficeDossiersRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/backoffice/facturation': {
      id: '/backoffice/facturation'
      path: '/facturation'
      fullPath: '/backoffice/facturation'
      preLoaderRoute: typeof BackofficeFacturationRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/backoffice/fournisseurs': {
      id: '/backoffice/fournisseurs'
      path: '/fournisseurs'
      fullPath: '/backoffice/fournisseurs'
      preLoaderRoute: typeof BackofficeFournisseursRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/backoffice/parametres': {
      id: '/backoffice/parametres'
      path: '/parametres'
      fullPath: '/backoffice/parametres'
      preLoaderRoute: typeof BackofficeParametresRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/backoffice/procedures': {
      id: '/backoffice/procedures'
      path: '/procedures'
      fullPath: '/backoffice/procedures'
      preLoaderRoute: typeof BackofficeProceduresRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/backoffice/rapports': {
      id: '/backoffice/rapports'
      path: '/rapports'
      fullPath: '/backoffice/rapports'
      preLoaderRoute: typeof BackofficeRapportsRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/backoffice/whatsapp': {
      id: '/backoffice/whatsapp'
      path: '/whatsapp'
      fullPath: '/backoffice/whatsapp'
      preLoaderRoute: typeof BackofficeWhatsappRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/site/': {
      id: '/site/'
      path: '/site'
      fullPath: '/site/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site/a-propos': {
      id: '/site/a-propos'
      path: '/site/a-propos'
      fullPath: '/site/a-propos'
      preLoaderRoute: typeof SiteAProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site/comment-ca-marche': {
      id: '/site/comment-ca-marche'
      path: '/site/comment-ca-marche'
      fullPath: '/site/comment-ca-marche'
      preLoaderRoute: typeof SiteCommentCaMarcheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site/contact': {
      id: '/site/contact'
      path: '/site/contact'
      fullPath: '/site/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site/demande': {
      id: '/site/demande'
      path: '/site/demande'
      fullPath: '/site/demande'
      preLoaderRoute: typeof SiteDemandeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site/services': {
      id: '/site/services'
      path: '/site/services'
      fullPath: '/site/services'
      preLoaderRoute: typeof SiteServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BackofficeRouteChildren {
  BackofficeClientsRoute: typeof BackofficeClientsRoute
  BackofficeCoursiersRoute: typeof BackofficeCoursiersRoute
  BackofficeDashboardRoute: typeof BackofficeDashboardRoute
  BackofficeDemandesRoute: typeof BackofficeDemandesRoute
  BackofficeDispatchRoute: typeof BackofficeDispatchRoute
  BackofficeDossiersRoute: typeof BackofficeDossiersRoute
  BackofficeFacturationRoute: typeof BackofficeFacturationRoute
  BackofficeFournisseursRoute: typeof BackofficeFournisseursRoute
  BackofficeParametresRoute: typeof BackofficeParametresRoute
  BackofficeProceduresRoute: typeof BackofficeProceduresRoute
  BackofficeRapportsRoute: typeof BackofficeRapportsRoute
  BackofficeWhatsappRoute: typeof BackofficeWhatsappRoute
  BackofficeIndexRoute: typeof BackofficeIndexRoute
}

const BackofficeRouteChildren: BackofficeRouteChildren = {
  BackofficeClientsRoute: BackofficeClientsRoute,
  BackofficeCoursiersRoute: BackofficeCoursiersRoute,
  BackofficeDashboardRoute: BackofficeDashboardRoute,
  BackofficeDemandesRoute: BackofficeDemandesRoute,
  BackofficeDispatchRoute: BackofficeDispatchRoute,
  BackofficeDossiersRoute: BackofficeDossiersRoute,
  BackofficeFacturationRoute: BackofficeFacturationRoute,
  BackofficeFournisseursRoute: BackofficeFournisseursRoute,
  BackofficeParametresRoute: BackofficeParametresRoute,
  BackofficeProceduresRoute: BackofficeProceduresRoute,
  BackofficeRapportsRoute: BackofficeRapportsRoute,
  BackofficeWhatsappRoute: BackofficeWhatsappRoute,
  BackofficeIndexRoute: BackofficeIndexRoute,
}

const BackofficeRouteWithChildren = BackofficeRoute._addFileChildren(
  BackofficeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BackofficeRoute: BackofficeRouteWithChildren,
  ConnexionRoute: ConnexionRoute,
  SiteAProposRoute: SiteAProposRoute,
  SiteCommentCaMarcheRoute: SiteCommentCaMarcheRoute,
  SiteContactRoute: SiteContactRoute,
  SiteDemandeRoute: SiteDemandeRoute,
  SiteServicesRoute: SiteServicesRoute,
  SiteIndexRoute: SiteIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
