/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as BackOfficeRouteImport } from './routes/back-office'
import { Route as BackofficeRouteImport } from './routes/backoffice'
import { Route as CommentCaMarcheRouteImport } from './routes/comment-ca-marche'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DemandeRouteImport } from './routes/demande'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as BackofficeIndexRouteImport } from './routes/backoffice.index'
import { Route as BackofficeDocumentsRouteImport } from './routes/backoffice.documents'
import { Route as BackofficeFournisseursRouteImport } from './routes/backoffice.fournisseurs'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const BackOfficeRoute = BackOfficeRouteImport.update({
  id: '/back-office',
  path: '/back-office',
  getParentRoute: () => rootRouteImport,
} as any)
const BackofficeRoute = BackofficeRouteImport.update({
  id: '/backoffice',
  path: '/backoffice',
  getParentRoute: () => rootRouteImport,
} as any)
const CommentCaMarcheRoute = CommentCaMarcheRouteImport.update({
  id: '/comment-ca-marche',
  path: '/comment-ca-marche',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DemandeRoute = DemandeRouteImport.update({
  id: '/demande',
  path: '/demande',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const BackofficeIndexRoute = BackofficeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeDocumentsRoute = BackofficeDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeFournisseursRoute = BackofficeFournisseursRouteImport.update({
  id: '/fournisseurs',
  path: '/fournisseurs',
  getParentRoute: () => BackofficeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/back-office': typeof BackOfficeRoute
  '/backoffice': typeof BackofficeRouteWithChildren
  '/comment-ca-marche': typeof CommentCaMarcheRoute
  '/connexion': typeof ConnexionRoute
  '/contact': typeof ContactRoute
  '/demande': typeof DemandeRoute
  '/services': typeof ServicesRoute
  '/backoffice/documents': typeof BackofficeDocumentsRoute
  '/backoffice/fournisseurs': typeof BackofficeFournisseursRoute
  '/backoffice/': typeof BackofficeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/back-office': typeof BackOfficeRoute
  '/comment-ca-marche': typeof CommentCaMarcheRoute
  '/connexion': typeof ConnexionRoute
  '/contact': typeof ContactRoute
  '/demande': typeof DemandeRoute
  '/services': typeof ServicesRoute
  '/backoffice/documents': typeof BackofficeDocumentsRoute
  '/backoffice/fournisseurs': typeof BackofficeFournisseursRoute
  '/backoffice': typeof BackofficeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/back-office': typeof BackOfficeRoute
  '/backoffice': typeof BackofficeRouteWithChildren
  '/comment-ca-marche': typeof CommentCaMarcheRoute
  '/connexion': typeof ConnexionRoute
  '/contact': typeof ContactRoute
  '/demande': typeof DemandeRoute
  '/services': typeof ServicesRoute
  '/backoffice/documents': typeof BackofficeDocumentsRoute
  '/backoffice/fournisseurs': typeof BackofficeFournisseursRoute
  '/backoffice/': typeof BackofficeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/back-office'
    | '/backoffice'
    | '/comment-ca-marche'
    | '/connexion'
    | '/contact'
    | '/demande'
    | '/services'
    | '/backoffice/documents'
    | '/backoffice/fournisseurs'
    | '/backoffice/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/back-office'
    | '/comment-ca-marche'
    | '/connexion'
    | '/contact'
    | '/demande'
    | '/services'
    | '/backoffice/documents'
    | '/backoffice/fournisseurs'
    | '/backoffice'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/back-office'
    | '/backoffice'
    | '/comment-ca-marche'
    | '/connexion'
    | '/contact'
    | '/demande'
    | '/services'
    | '/backoffice/documents'
    | '/backoffice/fournisseurs'
    | '/backoffice/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  BackOfficeRoute: typeof BackOfficeRoute
  BackofficeRoute: typeof BackofficeRouteWithChildren
  CommentCaMarcheRoute: typeof CommentCaMarcheRoute
  ConnexionRoute: typeof ConnexionRoute
  ContactRoute: typeof ContactRoute
  DemandeRoute: typeof DemandeRoute
  ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/back-office': {
      id: '/back-office'
      path: '/back-office'
      fullPath: '/back-office'
      preLoaderRoute: typeof BackOfficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backoffice': {
      id: '/backoffice'
      path: '/backoffice'
      fullPath: '/backoffice'
      preLoaderRoute: typeof BackofficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comment-ca-marche': {
      id: '/comment-ca-marche'
      path: '/comment-ca-marche'
      fullPath: '/comment-ca-marche'
      preLoaderRoute: typeof CommentCaMarcheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demande': {
      id: '/demande'
      path: '/demande'
      fullPath: '/demande'
      preLoaderRoute: typeof DemandeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backoffice/': {
      id: '/backoffice/'
      path: '/'
      fullPath: '/backoffice/'
      preLoaderRoute: typeof BackofficeIndexRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/backoffice/documents': {
      id: '/backoffice/documents'
      path: '/documents'
      fullPath: '/backoffice/documents'
      preLoaderRoute: typeof BackofficeDocumentsRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/backoffice/fournisseurs': {
      id: '/backoffice/fournisseurs'
      path: '/fournisseurs'
      fullPath: '/backoffice/fournisseurs'
      preLoaderRoute: typeof BackofficeFournisseursRouteImport
      parentRoute: typeof BackofficeRoute
    }
  }
}

interface BackofficeRouteChildren {
  BackofficeDocumentsRoute: typeof BackofficeDocumentsRoute
  BackofficeFournisseursRoute: typeof BackofficeFournisseursRoute
  BackofficeIndexRoute: typeof BackofficeIndexRoute
}

const BackofficeRouteChildren: BackofficeRouteChildren = {
  BackofficeDocumentsRoute: BackofficeDocumentsRoute,
  BackofficeFournisseursRoute: BackofficeFournisseursRoute,
  BackofficeIndexRoute: BackofficeIndexRoute,
}

const BackofficeRouteWithChildren = BackofficeRoute._addFileChildren(
  BackofficeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  BackOfficeRoute: BackOfficeRoute,
  BackofficeRoute: BackofficeRouteWithChildren,
  CommentCaMarcheRoute: CommentCaMarcheRoute,
  ConnexionRoute: ConnexionRoute,
  ContactRoute: ContactRoute,
  DemandeRoute: DemandeRoute,
  ServicesRoute: ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
